apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bcasaapba-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bcasaapba-java-springboot-gitops